CREATE USER pcoe WITH PASSWORD 'iRMUVCCU8Z7lyyvtizJt';
ALTER ROLE pcoe WITH SUPERUSER;

CREATE TABLE monitoring (
  date TIMESTAMP DEFAULT NULL,
  table_name VARCHAR(64) DEFAULT NULL,
  integration_statut VARCHAR(8) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  nb_lines INT DEFAULT NULL
);
